version: '2'
services:
  mysql:
    platform: linux/x86-64
    image: 'mysql:latest'
    restart: never
    volumes:
    - './mysql_data:/var/lib/mysql'
    environment:
    - MYSQL_ROOT_PASSWORD=root
    ports:
    - '3306:3306'
